PROJS_ROOT_DIR=..
include $(PROJS_ROOT_DIR)/make.inc

TASK_OBJS = $(ARCH)/main.o \
		$(ARCH)/src/InfoNES.o \
		$(ARCH)/src/InfoNES_Mapper.o \
		$(ARCH)/src/InfoNES_pAPU.o  \
		$(ARCH)/src/K6502.o

TASK = nesemu
BUILD_DIR = $(EWOKOS_ROOT_DIR)/system/build_$(ARCH)/$(HW)/rootfs/apps/$(TASK)

all: $(TASK)

$(TASK): $(TASK_OBJS) \
		$(SDK_DIR)/lib/libewoksys.a \
		$(SDK_DIR)/lib/libewokstl.a \
		$(SDK_DIR)/lib/libx++.a \
		$(SDK_DIR)/lib/libx.a \
		$(SDK_DIR)/lib/libfont.a \
		$(SDK_DIR)/lib/libgraph.a \
		$(SDK_DIR)/lib/libwidget++.a \
		$(SDK_DIR)/lib/libopenlibm.a \
		$(SDK_DIR)/lib/libcxx.a
	mkdir -p $(BUILD_DIR)
	$(LD) -Ttext=100 $(TASK_OBJS) -o $(BUILD_DIR)/$(TASK) $(LDFLAGS) $(EWOK_LIB_X) $(EWOK_LIB_GRAPH) -lsocket -lopenlibm $(EWOK_LIBC)  -lcxx
	cp -r res $(BUILD_DIR)

clean:
	rm -f $(TASK_OBJS)
